FROM postgres:11.2

# inspired by https://github.com/aruis/postgres-dockerfile/

MAINTAINER asah (adam.sah@gmail.com)

ENV PLV8_VERSION=2.3.11

RUN apt-get update -qq && apt-get install -qq --no-install-recommends \
    postgresql-server-dev-11 gcc make g++ pkg-config libc++-dev curl git python \
    ca-certificates

#
# plv8
#
RUN mkdir -p /plv8build
WORKDIR plv8build
RUN curl -s -o - -L https://github.com/plv8/plv8/archive/v${PLV8_VERSION}.tar.gz | tar -xzf -
RUN mkdir -p /plv8build/plv8-${PLV8_VERSION}/build
RUN cd /plv8build/plv8-${PLV8_VERSION} && env GIT_SSL_NO_VERIFY=true make USE_PGXS=1 && make USE_PGXS=1 install

#
# nodejs
#
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash - && apt-get install -qq --no-install-recommends nodejs

#
# plv8-modules
#
WORKDIR /var/lib/postgresql
RUN git clone https://github.com/jerrySievert/plv8-modules
WORKDIR plv8-modules
RUN npm install   # as root

RUN apt-get purge -qq -y gcc make g++ pkg-config libc++-dev postgresql-server-dev-11 curl git python 
RUN apt-get -qq -y autoremove && apt-get -qq -y clean
RUN rm -rf /var/lib/apt/lists/* /plv8build

# startup.sh is optional - you may want other stuff in there
#ADD startup.sh /docker-entrypoint-initdb.d

# recommended optimization

# recommended startup
# CMD su - postgres -c "/usr/lib/postgresql/11/bin/initdb -D /var/lib/postgresql/data; /usr/lib/postgresql/11/bin/postgres -D /var/lib/postgresql/data"


